package verifiers

import (
	"context"
	"io"
	"net/http"
	"strings"
	"time"

	"github.com/amchdd/subdomainabber/internal/core"
)

type AWSCloudFrontVerifier struct {
	client *http.Client
}

func NewAWSCloudFrontVerifier(cfg Config) *AWSCloudFrontVerifier {
	client := cfg.Client
	if client == nil {
		client = &http.Client{Timeout: 5 * time.Second}
	}
	return &AWSCloudFrontVerifier{
		client: client,
	}
}

func (v *AWSCloudFrontVerifier) Name() string {
	return "AWS CloudFront"
}

func (v *AWSCloudFrontVerifier) Verify(ctx context.Context, analysis *core.HostAnalysis) (*core.VerificationResult, error) {
	req, err := http.NewRequestWithContext(ctx, "GET", "http://"+analysis.Host, nil)
	if err != nil {
		return nil, err
	}

	resp, err := v.client.Do(req)
	if err != nil {
		req, _ = http.NewRequestWithContext(ctx, "GET", "https://"+analysis.Host, nil)
		resp, err = v.client.Do(req)
		if err != nil {
			return nil, err
		}
	}
	defer resp.Body.Close()

	bodyBytes, _ := io.ReadAll(io.LimitReader(resp.Body, 1<<20))
	bodyStr := string(bodyBytes)

	if resp.StatusCode == 403 && (strings.Contains(bodyStr, "Bad Request") || strings.Contains(bodyStr, "The request could not be satisfied")) && (strings.Contains(bodyStr, "Generated by CloudFront") || strings.Contains(resp.Header.Get("server"), "CloudFront")) {
		return &core.VerificationResult{
			Provider:   v.Name(),
			Verified:   true,
			Confidence: 90,
			Evidence:   "O Amazon CloudFront retornou uma assinatura de distribuição ausente; a possibilidade de reivindicação não foi comprovada.",
		}, nil
	}

	return nil, nil
}
